apiVersion: v1
kind: Service
metadata:
  name: gitlab-{{ template "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ template "postgresql.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.name }}
  selector:
    name: {{ template "postgresql.name" . }}
